language: csharp
solution: src/LaraUI.sln
mono: none
dotnet: 3.1.100
 
before_install:
 - sudo apt update
 - sudo apt install nuget nodejs npm
 - sudo apt-get install dotnet-sdk-2.1=2.1.300-1 
 - dotnet tool install coveralls.net --tool-path tools

install:
  - nuget restore src/LaraUI.sln

script:
 - cd src
 - echo "Debug" > environment.txt
 - cd LaraClient
 - npm install .
 - npm run-script build
 - cd ..
 - cd ..
 - dotnet build --configuration Debug src/LaraUI/LaraUI.csproj
 - dotnet build --configuration Debug --framework netcoreapp3.1 src/Tests/Tests.csproj
 - dotnet test --configuration Debug --framework netcoreapp3.1 src/Tests/Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=results.xml
 
after_script:
  - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
  - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
  - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_BRANCH
  - echo $REPO_COMMIT_AUTHOR
  - echo $REPO_COMMIT_AUTHOR_EMAIL
  - echo $REPO_COMMIT_MESSAGE
  - echo $TRAVIS_JOB_ID
  - ./tools/csmacnz.Coveralls --opencover -i src/Tests/results.xml --repoToken $COVERALLS_TOKEN --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName travis-ci  --useRelativePaths 
